### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by fernandex00** [hassio-addons/addon-magicmirror#1]
# hi, i found this addon it says it belongs to the community addons but i cant find it, the address of the repo Is the same as the Franck nijhof
> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
This addon is in development and not available or published yet.

**Comment by frenck** [comment]
Please do not use GitHub for support, but you already knew that since you asked the question on Discord as well.

**Comment by ludeeus** [comment]
@fernandex00 This add-on is still in developmet/research.
Once it's done it will show up.
For a list of current add-ons see https://github.com/hassio-addons/repository

<blockquote><img src="https://avatars1.githubusercontent.com/u/30772201?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/hassio-addons/repository">hassio-addons/repository</a></strong></div><div>Community Hass.io Add-ons for Home Assistant. Contribute to hassio-addons/repository development by creating an account on GitHub.</div></blockquote>
