### ISSUE TITLE
Cannot edit CSS

### ISSUE THREAD

**Issue by irakic89** [hassio-addons/addon-magicmirror#12]
# Problem/Motivation
Changing main.css or custom.css in \config\magicmirror\css\ folder doesn't make any visual changes to magic mirror after restart. 

## Expected behavior
When changing main.css in /config/magicmirror/css, changes should be applied after restart.

## Actual behavior
Nothing. Same css is loaded without changes (http response 304). 

## Steps to reproduce
Delete main.css from /config/magicmirror/css and after restart old main.css will be copied again. Change any line in main.css and those changes won't be applied after restart.

## Proposed changes
Automatically copy main.css and custom.css from /config/magicmirror/css to add-on folder in docker.

It's necessary to have easily accessible css file to edit.

**Comment by ludeeus** [comment]
This add-on is not released/not finished.
When it is, that will work.
